version: "3.7"

services:
  appsmith-editor:
    depends_on:
      - appsmith-internal-server
    build:
      context: ./../client/
      dockerfile: Dockerfile
    ports: 
      - "9080:80"
    networks:
      - appsmith
    restart: unless-stopped
  appsmith-rts:
    build: 
      context: ./../rts/
      dockerfile: Dockerfile
    environment:
      - APPSMITH_API_BASE_URL="http://appsmith-internal-server:8080"
    depends_on:
      - appsmith-internal-server
    networks:
      - appsmith
  appsmith-internal-server:
    build: .
    env_file: envs/docker.env
    environment:
      APPSMITH_REDIS_URL: "redis://redis:6379"
      APPSMITH_MONGODB_URI: "mongodb://mongo:27017/appsmith"
    depends_on:
      - mongo
      - redis
    ports:
      - "8080:8080"
    networks:
      - appsmith
    volumes:
      - ./container-volumes/git-storage:/data/git-storage
    restart: unless-stopped
  mongo:
    image: mongo:6.0.5
    environment:
      - MONGO_INITDB_DATABASE=appsmith
    volumes:
      - ./container-volumes/mongo:/data/db
    networks:
      - appsmith
    restart: unless-stopped
  redis:
    image: redis
    networks:
      - appsmith
    restart: unless-stopped
networks:
  appsmith:
    driver: bridge