version: "3.7"

services:
  appsmith-editor:
    depends_on:
      - appsmith-internal-server
    build:
      context: ./../client/
      dockerfile: Dockerfile
    ports: 
      - "9080:80"
    networks:
      - appsmith
  appsmith-internal-server:
    build: .
    env_file: envs/docker.env
    environment:
      APPSMITH_REDIS_URL: "redis://redis:6379"
      APPSMITH_MONGODB_URI: "mongodb://mongo:27017/appsmith"
    depends_on:
      - mongo
      - redis
    networks:
      - appsmith
    volumes:
      - ./container-volumes/git-storage:/data/git-storage

  mongo:
    image: mongo:5.0.15
    environment:
      - MONGO_INITDB_DATABASE=appsmith
    volumes:
      - ./container-volumes/mongo:/data/db
    networks:
      - appsmith

  redis:
    image: redis
    networks:
      - appsmith

networks:
  appsmith:
    driver: bridge